#!/usr/bin/env python3
"""Generate Python config types from the mq-bridge JSON schema.

The schema is produced on demand by the compiled extension
(``mq_bridge.config_schema()``), which derives it from the Rust models — the
same single source of truth used at runtime, so there is no checked-in schema
copy to drift. This script turns that schema into editor-friendly ``TypedDict``
definitions, giving key autocompletion when building ``Route.from_config`` /
``Publisher.from_config`` mappings.

Outputs (generated — do not edit by hand):
  - mq_bridge/config.pyi   rich TypedDicts for type checkers / editors
  - mq_bridge/config.py    runtime-safe aliases (no typing_extensions dep)

Run with:  uv run python scripts/gen_config_types.py   (needs the extension built)
A test (test_config_types.py) asserts the checked-in output is up to date.
"""

from __future__ import annotations

import json
from pathlib import Path

PKG_DIR = Path(__file__).resolve().parents[1]

PYI_PATH = PKG_DIR / "mq_bridge" / "config.pyi"
PY_PATH = PKG_DIR / "mq_bridge" / "config.py"


def load_schema() -> dict:
    """Generate the schema ad hoc from the compiled extension."""
    from mq_bridge import config_schema

    return config_schema()

HEADER = (
    "# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.\n"
    "# Do not edit by hand; re-run the generator after changing the schema.\n"
)


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def non_null_branches(branches: list) -> tuple[list, bool]:
    """Split a oneOf/anyOf branch list into (non-null branches, nullable?)."""
    nullable = any(b.get("type") == "null" for b in branches)
    return [b for b in branches if b.get("type") != "null"], nullable


def type_expr(schema: dict) -> str:
    """Render a JSON-schema property node as a Python type annotation string."""
    if "$ref" in schema:
        return ref_name(schema["$ref"])

    if "const" in schema:
        return f"Literal[{json.dumps(schema['const'])}]"

    if "enum" in schema:
        return "Literal[" + ", ".join(json.dumps(v) for v in schema["enum"]) + "]"

    for combinator in ("oneOf", "anyOf"):
        if combinator in schema:
            branches, nullable = non_null_branches(schema[combinator])
            inner = [type_expr(b) for b in branches] or ["Any"]
            rendered = inner[0] if len(inner) == 1 else "Union[" + ", ".join(inner) + "]"
            return f"Optional[{rendered}]" if nullable else rendered

    jtype = schema.get("type")
    if isinstance(jtype, list):  # e.g. ["integer", "null"]
        nullable = "null" in jtype
        concrete = [t for t in jtype if t != "null"]
        base = _scalar({**schema, "type": concrete[0]}) if concrete else "Any"
        return f"Optional[{base}]" if nullable else base

    return _scalar(schema)


def _scalar(schema: dict) -> str:
    jtype = schema.get("type")
    if jtype == "string":
        return "str"
    if jtype == "integer":
        return "int"
    if jtype == "number":
        return "float"
    if jtype == "boolean":
        return "bool"
    if jtype == "array":
        items = schema.get("items")
        return f"List[{type_expr(items)}]" if isinstance(items, dict) else "List[Any]"
    if jtype == "object":
        addl = schema.get("additionalProperties")
        if isinstance(addl, dict):
            return f"Dict[str, {type_expr(addl)}]"
        return "Dict[str, Any]"
    return "Any"


def merged_variant_fields(defn: dict) -> dict | None:
    """For tagged-union defs (Endpoint, Middleware) where each oneOf branch is an
    object with a single required key, merge every key into one optional mapping."""
    branches = defn.get("oneOf")
    if not branches:
        return None
    fields: dict[str, str] = {}
    for branch in branches:
        props = branch.get("properties")
        if branch.get("type") != "object" or not props:
            return None
        for key, sub in props.items():
            fields[key] = type_expr(sub)
    # Include any shared properties declared alongside the union (e.g. middlewares).
    for key, sub in defn.get("properties", {}).items():
        fields[key] = type_expr(sub)
    return fields


def is_string_enum(defn: dict) -> list | None:
    branches = defn.get("oneOf")
    if branches and all("const" in b for b in branches):
        return [b["const"] for b in branches]
    if "enum" in defn and defn.get("type") == "string":
        return list(defn["enum"])
    return None


def doc_comment(defn: dict) -> str:
    desc = defn.get("description")
    if not desc:
        return ""
    first = desc.strip().splitlines()[0]
    return f'    """{first}"""\n'


def render_typeddict(name: str, fields: dict, required: set, defn: dict) -> str:
    lines = [f"class {name}(TypedDict, total=False):"]
    doc = doc_comment(defn)
    if doc:
        lines.append(doc.rstrip("\n"))
    if not fields:
        lines.append("    pass")
    for key in sorted(fields):
        expr = fields[key]
        wrapped = f"Required[{expr}]" if key in required else expr
        lines.append(f"    {key}: {wrapped}")
    return "\n".join(lines) + "\n"


def generate() -> tuple[str, str]:
    schema = load_schema()
    defs = schema["$defs"]

    typeddicts: list[str] = []
    aliases: list[str] = []
    runtime_typeddicts: list[str] = []
    runtime_enums: list[str] = []

    for name, defn in sorted(defs.items()):
        enum_values = is_string_enum(defn)
        if enum_values is not None:
            literal = "Literal[" + ", ".join(json.dumps(v) for v in enum_values) + "]"
            aliases.append(f"{name} = {literal}")
            runtime_enums.append(name)
            continue

        merged = merged_variant_fields(defn)
        if merged is not None:
            typeddicts.append(render_typeddict(name, merged, set(), defn))
            runtime_typeddicts.append(name)
            continue

        if defn.get("type") == "object" or "properties" in defn:
            props = defn.get("properties", {})
            fields = {key: type_expr(sub) for key, sub in props.items()}
            required = set(defn.get("required", []))
            typeddicts.append(render_typeddict(name, fields, required, defn))
            runtime_typeddicts.append(name)
            continue

        # Anything else: fall back to a permissive alias.
        aliases.append(f"{name} = {type_expr(defn)}")
        runtime_enums.append(name)

    # Top-level convenience types. The schema's root is a map of route-name ->
    # Route; the document form ({routes, publishers}) and friendly aliases are
    # added here since they are part of the Python from_config surface.
    extra = (
        "RouteConfig = Route\n"
        "EndpointConfig = Endpoint\n"
        "RoutesConfig = Dict[str, Route]\n"
        "\n"
        "class ConfigDocument(TypedDict, total=False):\n"
        '    """Top-level config accepted by from_config / from_yaml_str."""\n'
        "    routes: Dict[str, Route]\n"
        "    publishers: Dict[str, Endpoint]\n"
    )

    pyi = (
        HEADER
        + "from __future__ import annotations\n\n"
        + "from typing import Any, Dict, List, Literal, Optional, Union\n\n"
        + "from typing_extensions import Required, TypedDict\n\n\n"
        + "\n\n".join(typeddicts)
        + "\n\n"
        + "\n".join(aliases)
        + "\n\n\n"
        + extra
    )

    # Runtime module: no typing_extensions dependency. TypedDicts become `dict`
    # and string enums become `str`, which are valid as annotations at runtime
    # (type checkers use config.pyi, not this file).
    runtime_names = sorted(set(runtime_typeddicts + runtime_enums)) + [
        "RouteConfig",
        "EndpointConfig",
        "RoutesConfig",
        "ConfigDocument",
    ]
    runtime_lines = [HEADER, "from __future__ import annotations\n"]
    for name in sorted(runtime_typeddicts):
        runtime_lines.append(f"{name} = dict")
    for name in sorted(runtime_enums):
        runtime_lines.append(f"{name} = str")
    runtime_lines.append("RouteConfig = Route")
    runtime_lines.append("EndpointConfig = Endpoint")
    runtime_lines.append("RoutesConfig = dict")
    runtime_lines.append("ConfigDocument = dict")
    runtime_lines.append("")
    runtime_lines.append("__all__ = [")
    for name in sorted(set(runtime_names)):
        runtime_lines.append(f'    "{name}",')
    runtime_lines.append("]")
    py = "\n".join(runtime_lines) + "\n"

    return pyi, py


def main() -> None:
    pyi, py = generate()
    PYI_PATH.write_text(pyi)
    PY_PATH.write_text(py)
    print(f"wrote {PYI_PATH.relative_to(PKG_DIR)}")
    print(f"wrote {PY_PATH.relative_to(PKG_DIR)}")


if __name__ == "__main__":
    main()
