[package]
name = "mq-bridge-node"
version.workspace = true
edition = "2021"
publish = false
description = "Node.js bindings for mq-bridge, an async message-bridging library"
license = "MIT"
repository = "https://github.com/marcomq/mq-bridge"

[lib]
name = "mq_bridge_node"
crate-type = ["cdylib"]
doctest = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes = { workspace = true, features = ["serde"] }
fast-uuid-v7.workspace = true
mq-bridge = { path = "../.." }
mq-bridge-bindings-common = { path = "../../bindings-common" }
napi = { version = "3", features = ["serde-json", "async"] }
napi-derive = "3"
schemars = { version = "1.2", optional = true }
serde_json.workspace = true
serde_yaml_ng.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tracing.workspace = true

[build-dependencies]
napi-build = "2"

[features]
default = ["full"]
middleware = ["mq-bridge/middleware"]
full = ["mq-bridge/full", "schema"]
basic = ["http", "nats", "mqtt", "websocket", "zeromq", "rustls-ring", "schema"]
dedup = ["mq-bridge/dedup"]
metrics = ["mq-bridge/metrics"]
schema = ["dep:schemars", "mq-bridge/schema"]
test-utils = ["mq-bridge/test-utils"]
kafka = ["mq-bridge/kafka"]
amqp = ["mq-bridge/amqp"]
nats = ["mq-bridge/nats"]
mongodb = ["mq-bridge/mongodb"]
mqtt = ["mq-bridge/mqtt"]
http = ["mq-bridge/http"]
websocket = ["mq-bridge/websocket"]
aws = ["mq-bridge/aws"]
ibm-mq = ["mq-bridge/ibm-mq"]
ibm-mq-static = ["mq-bridge/ibm-mq-static"]
zeromq = ["mq-bridge/zeromq"]
grpc = ["mq-bridge/grpc"]
sqlx = ["mq-bridge/sqlx"]
rustls-ring = ["mq-bridge/rustls-ring"]
rustls-aws-lc = ["mq-bridge/rustls-aws-lc"]
