# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from typing_extensions import Required, TypedDict


class AmqpConfig(TypedDict, total=False):
    """General AMQP connection configuration."""
    delayed_ack: bool
    exchange: Optional[str]
    no_declare_queue: bool
    no_persistence: bool
    password: Optional[str]
    prefetch_count: Optional[int]
    queue: Optional[str]
    subscribe_mode: bool
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]


class AwsConfig(TypedDict, total=False):
    access_key: Optional[str]
    binary_payload_mode: bool
    endpoint_url: Optional[str]
    max_messages: Optional[int]
    queue_url: Optional[str]
    region: Optional[str]
    secret_key: Optional[str]
    session_token: Optional[str]
    topic_arn: Optional[str]
    wait_time_seconds: Optional[int]


class BufferMiddleware(TypedDict, total=False):
    """Publisher-side buffer middleware configuration."""
    max_delay_ms: Required[int]
    max_messages: Required[int]


class ClickHouseConfig(TypedDict, total=False):
    """ClickHouse endpoint configuration (talks the ClickHouse HTTP interface)."""
    async_insert: bool
    checkpoint_store: Optional[str]
    columns: Optional[Dict[str, str]]
    connect_timeout_ms: Optional[int]
    cursor_column: Optional[str]
    cursor_id: Optional[str]
    database: Optional[str]
    max_polling_interval_ms: Optional[int]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    request_timeout_ms: Optional[int]
    select_columns: Optional[str]
    table: Required[str]
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]
    wait_for_async_insert: Optional[bool]


class CookieJarMiddleware(TypedDict, total=False):
    """Cookie/session jar middleware configuration."""
    capture_metadata_keys: List[str]
    cookie_metadata_key: str
    export_metadata_prefix: Optional[str]
    inject_metadata: Dict[str, str]
    set_cookie_metadata_key: str
    shared_scope: Optional[str]


class DeadLetterQueueMiddleware(TypedDict, total=False):
    """Dead-Letter Queue (DLQ) middleware configuration."""
    endpoint: Required[Endpoint]


class DeduplicationMiddleware(TypedDict, total=False):
    """Deduplication middleware configuration."""
    sled_path: Required[str]
    ttl_seconds: Required[int]


class DelayMiddleware(TypedDict, total=False):
    """Delay middleware configuration."""
    delay_ms: Required[int]


class Endpoint(TypedDict, total=False):
    """Represents a connection point for messages, which can be a source (input) or a sink (output)."""
    amqp: AmqpConfig
    aws: AwsConfig
    clickhouse: ClickHouseConfig
    custom: Dict[str, Any]
    fanout: List[Endpoint]
    file: FileConfig
    grpc: GrpcConfig
    http: HttpConfig
    ibmmq: IbmMqConfig
    kafka: KafkaConfig
    memory: MemoryConfig
    middlewares: List[Middleware]
    mongodb: MongoDbConfig
    mqtt: MqttConfig
    nats: NatsConfig
    null: Any
    postgres_cdc: PostgresCdcConfig
    reader: Endpoint
    redis_streams: RedisStreamsConfig
    ref: str
    response: ResponseConfig
    sled: SledConfig
    sqlx: SqlxConfig
    static: StaticConfig
    stream_buffer: StreamBufferConfig
    switch: SwitchConfig
    websocket: WebSocketConfig
    zeromq: ZeroMqConfig


class FileConfig(TypedDict, total=False):
    delimiter: Optional[str]
    format: FileFormat
    path: Required[str]


class GrpcConfig(TypedDict, total=False):
    concurrency_limit_per_connection: Optional[int]
    http2_keepalive_interval_ms: Optional[int]
    http2_keepalive_timeout_ms: Optional[int]
    initial_connection_window_size: Optional[int]
    initial_stream_window_size: Optional[int]
    max_decoding_message_size: Optional[int]
    server_mode: bool
    shared: Optional[bool]
    timeout_ms: Optional[int]
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]


class HttpConfig(TypedDict, total=False):
    """General HTTP connection configuration."""
    basic_auth: Optional[List[Any]]
    batch_concurrency: Optional[int]
    compression_enabled: bool
    compression_threshold_bytes: Optional[int]
    concurrency_limit: Optional[int]
    custom_headers: Dict[str, str]
    fire_and_forget: bool
    inline_response_fast_path: Optional[bool]
    internal_buffer_size: Optional[int]
    message_id_header: Optional[str]
    method: Optional[str]
    path: Optional[str]
    pool_idle_timeout_ms: Optional[int]
    receive_streamable: bool
    request_timeout_ms: Optional[int]
    server_protocol: HttpServerProtocol
    shared: Optional[bool]
    stream_response_to: Optional[Endpoint]
    tcp_keepalive_ms: Optional[int]
    tls: TlsConfig
    url: Required[str]
    workers: Optional[int]


class IbmMqConfig(TypedDict, total=False):
    """Connection settings for the IBM MQ Queue Manager."""
    channel: Required[str]
    disable_status_inq: bool
    internal_buffer_size: Optional[int]
    max_message_size: int
    password: Optional[str]
    queue: Optional[str]
    queue_manager: Required[str]
    tls: IbmTlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]
    wait_timeout_ms: int


class IbmTlsConfig(TypedDict, total=False):
    """TLS configuration for the IBM MQ native client."""
    accept_invalid_certs: bool
    cert_file: Optional[str]
    cert_password: Optional[str]
    cipher_spec: Optional[str]
    key_repository: Optional[str]
    key_repository_password: Optional[str]
    required: bool


class KafkaConfig(TypedDict, total=False):
    """General Kafka connection configuration."""
    consumer_options: Optional[List[List[Any]]]
    delayed_ack: bool
    group_id: Optional[str]
    partition_key: Optional[str]
    partitions: Optional[int]
    password: Optional[str]
    producer_options: Optional[List[List[Any]]]
    shared: Optional[bool]
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]


class LimiterMiddleware(TypedDict, total=False):
    """Throughput limiter middleware configuration."""
    messages_per_second: Required[float]


class MemoryConfig(TypedDict, total=False):
    capacity: Optional[int]
    enable_nack: bool
    request_reply: bool
    request_timeout_ms: Optional[int]
    subscribe_mode: bool
    topic: str
    url: str


class MetricsMiddleware(TypedDict, total=False):
    """Metrics middleware configuration."""
    pass


class Middleware(TypedDict, total=False):
    """An enumeration of all supported middleware types."""
    buffer: BufferMiddleware
    cookie_jar: CookieJarMiddleware
    custom: Dict[str, Any]
    deduplication: DeduplicationMiddleware
    delay: DelayMiddleware
    dlq: DeadLetterQueueMiddleware
    limiter: LimiterMiddleware
    metrics: MetricsMiddleware
    random_panic: RandomPanicMiddleware
    retry: RetryMiddleware
    weak_join: WeakJoinMiddleware


class MongoDbConfig(TypedDict, total=False):
    """General MongoDB connection configuration."""
    capped_size_bytes: Optional[int]
    change_stream: bool
    checkpoint_store: Optional[str]
    collection: Optional[str]
    consume: Optional[MongoConsume]
    cursor_id: Optional[str]
    database: Required[str]
    format: MongoDbFormat
    meta_collection: Optional[str]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    receive_query: Optional[str]
    reply_polling_ms: Optional[int]
    request_reply: bool
    request_timeout_ms: Optional[int]
    shared: Optional[bool]
    tls: TlsConfig
    ttl_seconds: Optional[int]
    url: Required[str]
    username: Optional[str]


class MqttConfig(TypedDict, total=False):
    """General MQTT connection configuration."""
    clean_session: bool
    client_id: Optional[str]
    delayed_ack: bool
    keep_alive_seconds: Optional[int]
    max_inflight: Optional[int]
    password: Optional[str]
    protocol: MqttProtocol
    qos: Optional[int]
    queue_capacity: Optional[int]
    session_expiry_interval: Optional[int]
    tls: TlsConfig
    topic: Optional[str]
    url: Required[str]
    username: Optional[str]


class NatsConfig(TypedDict, total=False):
    """General NATS connection configuration."""
    deduplicate: bool
    delayed_ack: bool
    deliver_policy: Optional[NatsDeliverPolicy]
    no_jetstream: bool
    password: Optional[str]
    prefetch_count: Optional[int]
    request_reply: bool
    request_timeout_ms: Optional[int]
    shared: Optional[bool]
    stream: Optional[str]
    stream_max_bytes: Optional[int]
    stream_max_messages: Optional[int]
    subject: Optional[str]
    subscriber_mode: bool
    tls: TlsConfig
    token: Optional[str]
    url: Required[str]
    username: Optional[str]


class PostgresCdcConfig(TypedDict, total=False):
    """Postgres logical-replication CDC source (pgoutput). Source-only."""
    checkpoint_store: Optional[str]
    create_slot: bool
    cursor_id: Optional[str]
    publication: Required[str]
    slot_name: str
    status_interval_ms: int
    temporary_slot: bool
    tls: TlsConfig
    url: Required[str]


class RandomPanicMiddleware(TypedDict, total=False):
    """Middleware for fault injection testing."""
    enabled: bool
    mode: FaultMode
    trigger_on_message: Optional[int]


class RedisStreamsConfig(TypedDict, total=False):
    """Configuration for a Redis Streams endpoint."""
    approx_trim: Optional[bool]
    block_ms: Optional[int]
    consumer_name: Optional[str]
    group: Optional[str]
    internal_buffer_size: Optional[int]
    maxlen: Optional[int]
    password: Optional[str]
    read_from_start: bool
    reader_connections: Optional[int]
    redelivery_timeout_ms: Optional[int]
    stream: Optional[str]
    subscriber_mode: bool
    url: Required[str]
    username: Optional[str]


class ResponseConfig(TypedDict, total=False):
    pass


class RetryMiddleware(TypedDict, total=False):
    """Retry middleware configuration."""
    initial_interval_ms: int
    max_attempts: int
    max_interval_ms: int
    multiplier: float


class Route(TypedDict, total=False):
    """Defines a single message processing route from an input to an output."""
    allow_fault_injection: bool
    batch_size: int
    commit_concurrency_limit: int
    concurrency: int
    description: str
    empty_batch_delay_ms: int
    exit_on_empty: bool
    input: Required[Endpoint]
    output: Endpoint
    reconnect_interval_ms: int
    startup_timeout_ms: int


class SledConfig(TypedDict, total=False):
    """General Sled database configuration"""
    delete_after_read: bool
    path: Required[str]
    read_from_start: bool
    tree: Optional[str]


class SqlxConfig(TypedDict, total=False):
    """General SQLx connection configuration."""
    acquire_timeout_ms: Optional[int]
    auto_create_table: bool
    bulk_copy: bool
    checkpoint_store: Optional[str]
    cursor_column: Optional[str]
    cursor_id: Optional[str]
    delete_after_read: bool
    idle_timeout_ms: Optional[int]
    insert_query: Optional[str]
    max_connections: Optional[int]
    max_lifetime_ms: Optional[int]
    max_polling_interval_ms: Optional[int]
    min_connections: Optional[int]
    password: Optional[str]
    polling_interval_ms: Optional[int]
    publication: Optional[str]
    select_query: Optional[str]
    shared: Optional[bool]
    slot_name: Optional[str]
    table: Required[str]
    tls: TlsConfig
    url: Required[str]
    username: Optional[str]


class StreamBufferConfig(TypedDict, total=False):
    """Configuration for the correlated in-process stream response buffer."""
    capacity: Optional[int]
    correlation_id: Optional[str]
    topic: Required[str]


class SwitchConfig(TypedDict, total=False):
    cases: Required[Dict[str, Endpoint]]
    default: Optional[Endpoint]
    metadata_key: Required[str]


class TlsConfig(TypedDict, total=False):
    """TLS configuration for secure connections."""
    accept_invalid_certs: bool
    ca_file: Optional[str]
    cert_file: Optional[str]
    cert_password: Optional[str]
    key_file: Optional[str]
    required: bool


class WeakJoinMiddleware(TypedDict, total=False):
    """Weak Join middleware configuration."""
    branch_by: Optional[str]
    expected_count: Required[int]
    group_by: Required[str]
    on_timeout: WeakJoinTimeout
    required: List[str]
    timeout_ms: Required[int]


class WebSocketConfig(TypedDict, total=False):
    """WebSocket connection configuration."""
    backlog: Optional[int]
    execution_mode: WebSocketExecutionMode
    message_id_header: Optional[str]
    path: Optional[str]
    routed_queue_capacity: Optional[int]
    url: Required[str]


class ZeroMqConfig(TypedDict, total=False):
    bind: bool
    format: ZeroMqFormat
    internal_buffer_size: Optional[int]
    socket_type: Optional[ZeroMqSocketType]
    topic: Optional[str]
    url: Required[str]


FaultMode = Literal["panic", "disconnect", "timeout", "json_format_error", "nack"]
FileFormat = Literal["normal", "json", "text", "raw", "csv"]
HttpServerProtocol = Literal["auto", "http1_only", "http2_only"]
MongoConsume = Literal["consumer", "subscriber", "capture_new", "capture_all"]
MongoDbFormat = Literal["normal", "json", "text", "raw"]
MqttProtocol = Literal["v5", "v3"]
NatsDeliverPolicy = Literal["all", "last", "new", "last_per_subject"]
StaticConfig = Union[str, Dict[str, Any]]
WeakJoinTimeout = Literal["fire", "discard"]
WebSocketExecutionMode = Literal["auto", "direct_only", "routed"]
ZeroMqFormat = Literal["json", "raw", "raw_framed"]
ZeroMqSocketType = Literal["push", "pull", "pub", "sub", "req", "rep"]


RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = Dict[str, Route]

class ConfigDocument(TypedDict, total=False):
    """Top-level config accepted by from_file / from_str / from_config."""
    routes: Dict[str, Route]
    publishers: Dict[str, Endpoint]
