# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.

from __future__ import annotations

AmqpConfig = dict
AwsConfig = dict
BufferMiddleware = dict
ClickHouseConfig = dict
CookieJarMiddleware = dict
DeadLetterQueueMiddleware = dict
DeduplicationMiddleware = dict
DelayMiddleware = dict
Endpoint = dict
FileConfig = dict
GrpcConfig = dict
HttpConfig = dict
IbmMqConfig = dict
IbmTlsConfig = dict
KafkaConfig = dict
LimiterMiddleware = dict
MemoryConfig = dict
MetricsMiddleware = dict
Middleware = dict
MongoDbConfig = dict
MqttConfig = dict
NatsConfig = dict
PostgresCdcConfig = dict
RandomPanicMiddleware = dict
RedisStreamsConfig = dict
ResponseConfig = dict
RetryMiddleware = dict
Route = dict
SledConfig = dict
SqlxConfig = dict
StreamBufferConfig = dict
SwitchConfig = dict
TlsConfig = dict
WeakJoinMiddleware = dict
WebSocketConfig = dict
ZeroMqConfig = dict
FaultMode = str
FileFormat = str
HttpServerProtocol = str
MongoConsume = str
MongoDbFormat = str
MqttProtocol = str
NatsDeliverPolicy = str
StaticConfig = str
WeakJoinTimeout = str
WebSocketExecutionMode = str
ZeroMqFormat = str
ZeroMqSocketType = str
RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = dict
ConfigDocument = dict

__all__ = [
    "AmqpConfig",
    "AwsConfig",
    "BufferMiddleware",
    "ClickHouseConfig",
    "ConfigDocument",
    "CookieJarMiddleware",
    "DeadLetterQueueMiddleware",
    "DeduplicationMiddleware",
    "DelayMiddleware",
    "Endpoint",
    "EndpointConfig",
    "FaultMode",
    "FileConfig",
    "FileFormat",
    "GrpcConfig",
    "HttpConfig",
    "HttpServerProtocol",
    "IbmMqConfig",
    "IbmTlsConfig",
    "KafkaConfig",
    "LimiterMiddleware",
    "MemoryConfig",
    "MetricsMiddleware",
    "Middleware",
    "MongoConsume",
    "MongoDbConfig",
    "MongoDbFormat",
    "MqttConfig",
    "MqttProtocol",
    "NatsConfig",
    "NatsDeliverPolicy",
    "PostgresCdcConfig",
    "RandomPanicMiddleware",
    "RedisStreamsConfig",
    "ResponseConfig",
    "RetryMiddleware",
    "Route",
    "RouteConfig",
    "RoutesConfig",
    "SledConfig",
    "SqlxConfig",
    "StaticConfig",
    "StreamBufferConfig",
    "SwitchConfig",
    "TlsConfig",
    "WeakJoinMiddleware",
    "WeakJoinTimeout",
    "WebSocketConfig",
    "WebSocketExecutionMode",
    "ZeroMqConfig",
    "ZeroMqFormat",
    "ZeroMqSocketType",
]
