# Generated by scripts/gen_config_types.py from mq-bridge.schema.json.
# Do not edit by hand; re-run the generator after changing the schema.
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from typing_extensions import Required, TypedDict


class AmqpConfig(TypedDict, total=False):
    """General AMQP connection configuration."""
    url: Required[str]
    queue: Optional[str]
    subscribe_mode: bool
    username: Optional[str]
    password: Optional[str]
    tls: TlsConfig
    exchange: Optional[str]
    prefetch_count: Optional[int]
    no_persistence: bool
    no_declare_queue: bool
    delayed_ack: bool


class AwsConfig(TypedDict, total=False):
    queue_url: Optional[str]
    topic_arn: Optional[str]
    region: Optional[str]
    endpoint_url: Optional[str]
    access_key: Optional[str]
    secret_key: Optional[str]
    session_token: Optional[str]
    max_messages: Optional[int]
    wait_time_seconds: Optional[int]
    binary_payload_mode: bool


class BufferMiddleware(TypedDict, total=False):
    """Publisher-side buffer middleware configuration."""
    max_messages: Required[int]
    max_delay_ms: Required[int]


class CookieJarMiddleware(TypedDict, total=False):
    """Cookie/session jar middleware configuration."""
    shared_scope: Optional[str]
    cookie_metadata_key: str
    set_cookie_metadata_key: str
    capture_metadata_keys: List[str]
    export_metadata_prefix: Optional[str]
    inject_metadata: Dict[str, str]


class DeadLetterQueueMiddleware(TypedDict, total=False):
    """Dead-Letter Queue (DLQ) middleware configuration."""
    endpoint: Required[Endpoint]


class DeduplicationMiddleware(TypedDict, total=False):
    """Deduplication middleware configuration."""
    sled_path: Required[str]
    ttl_seconds: Required[int]


class DelayMiddleware(TypedDict, total=False):
    """Delay middleware configuration."""
    delay_ms: Required[int]


class Endpoint(TypedDict, total=False):
    """Represents a connection point for messages, which can be a source (input) or a sink (output)."""
    aws: AwsConfig
    kafka: KafkaConfig
    nats: NatsConfig
    file: FileConfig
    static: StaticConfig
    ref: str
    memory: MemoryConfig
    sled: SledConfig
    amqp: AmqpConfig
    mongodb: MongoDbConfig
    mqtt: MqttConfig
    http: HttpConfig
    websocket: WebSocketConfig
    ibmmq: IbmMqConfig
    zeromq: ZeroMqConfig
    grpc: GrpcConfig
    sqlx: SqlxConfig
    fanout: List[Endpoint]
    stream_buffer: StreamBufferConfig
    switch: SwitchConfig
    response: ResponseConfig
    reader: Endpoint
    custom: Dict[str, Any]
    null: Any
    middlewares: List[Middleware]


class FileConfig(TypedDict, total=False):
    path: Required[str]
    delimiter: Optional[str]
    format: FileFormat


class GrpcConfig(TypedDict, total=False):
    url: Required[str]
    topic: Optional[str]
    timeout_ms: Optional[int]
    tls: TlsConfig
    server_mode: bool
    initial_stream_window_size: Optional[int]
    initial_connection_window_size: Optional[int]
    concurrency_limit_per_connection: Optional[int]
    http2_keepalive_interval_ms: Optional[int]
    http2_keepalive_timeout_ms: Optional[int]
    max_decoding_message_size: Optional[int]


class HttpConfig(TypedDict, total=False):
    """General HTTP connection configuration."""
    url: Required[str]
    path: Optional[str]
    method: Optional[str]
    tls: TlsConfig
    workers: Optional[int]
    message_id_header: Optional[str]
    request_timeout_ms: Optional[int]
    internal_buffer_size: Optional[int]
    fire_and_forget: bool
    receive_streamable: bool
    inline_response_fast_path: Optional[bool]
    server_protocol: HttpServerProtocol
    stream_response_to: Optional[Endpoint]
    batch_concurrency: Optional[int]
    tcp_keepalive_ms: Optional[int]
    pool_idle_timeout_ms: Optional[int]
    compression_enabled: bool
    compression_threshold_bytes: Optional[int]
    concurrency_limit: Optional[int]
    basic_auth: Optional[List[Any]]
    custom_headers: Dict[str, str]


class IbmMqConfig(TypedDict, total=False):
    """Connection settings for the IBM MQ Queue Manager."""
    url: Required[str]
    queue: Optional[str]
    topic: Optional[str]
    queue_manager: Required[str]
    channel: Required[str]
    username: Optional[str]
    password: Optional[str]
    cipher_spec: Optional[str]
    tls: TlsConfig
    max_message_size: int
    wait_timeout_ms: int
    internal_buffer_size: Optional[int]
    disable_status_inq: bool


class KafkaConfig(TypedDict, total=False):
    """General Kafka connection configuration."""
    url: Required[str]
    topic: Optional[str]
    username: Optional[str]
    password: Optional[str]
    tls: TlsConfig
    group_id: Optional[str]
    delayed_ack: bool
    producer_options: Optional[List[List[Any]]]
    consumer_options: Optional[List[List[Any]]]


class LimiterMiddleware(TypedDict, total=False):
    """Throughput limiter middleware configuration."""
    messages_per_second: Required[float]


class MemoryConfig(TypedDict, total=False):
    topic: str
    capacity: Optional[int]
    request_reply: bool
    request_timeout_ms: Optional[int]
    subscribe_mode: bool
    enable_nack: bool
    url: str


class MetricsMiddleware(TypedDict, total=False):
    """Metrics middleware configuration."""
    pass


class Middleware(TypedDict, total=False):
    """An enumeration of all supported middleware types."""
    deduplication: DeduplicationMiddleware
    metrics: MetricsMiddleware
    dlq: DeadLetterQueueMiddleware
    retry: RetryMiddleware
    random_panic: RandomPanicMiddleware
    delay: DelayMiddleware
    weak_join: WeakJoinMiddleware
    limiter: LimiterMiddleware
    buffer: BufferMiddleware
    cookie_jar: CookieJarMiddleware
    custom: Dict[str, Any]


class MongoDbConfig(TypedDict, total=False):
    """General MongoDB connection configuration."""
    url: Required[str]
    collection: Optional[str]
    username: Optional[str]
    password: Optional[str]
    tls: TlsConfig
    database: Required[str]
    polling_interval_ms: Optional[int]
    reply_polling_ms: Optional[int]
    request_reply: bool
    change_stream: bool
    request_timeout_ms: Optional[int]
    ttl_seconds: Optional[int]
    capped_size_bytes: Optional[int]
    format: MongoDbFormat
    cursor_id: Optional[str]
    receive_query: Optional[str]
    meta_collection: Optional[str]


class MqttConfig(TypedDict, total=False):
    """General MQTT connection configuration."""
    url: Required[str]
    topic: Optional[str]
    username: Optional[str]
    password: Optional[str]
    tls: TlsConfig
    client_id: Optional[str]
    queue_capacity: Optional[int]
    max_inflight: Optional[int]
    qos: Optional[int]
    clean_session: bool
    keep_alive_seconds: Optional[int]
    protocol: MqttProtocol
    session_expiry_interval: Optional[int]
    delayed_ack: bool


class NatsConfig(TypedDict, total=False):
    """General NATS connection configuration."""
    url: Required[str]
    subject: Optional[str]
    stream: Optional[str]
    username: Optional[str]
    password: Optional[str]
    tls: TlsConfig
    token: Optional[str]
    request_reply: bool
    request_timeout_ms: Optional[int]
    delayed_ack: bool
    no_jetstream: bool
    subscriber_mode: bool
    stream_max_messages: Optional[int]
    deliver_policy: Optional[NatsDeliverPolicy]
    stream_max_bytes: Optional[int]
    prefetch_count: Optional[int]


class RandomPanicMiddleware(TypedDict, total=False):
    """Middleware for fault injection testing."""
    mode: FaultMode
    trigger_on_message: Optional[int]
    enabled: bool


class ResponseConfig(TypedDict, total=False):
    pass


class RetryMiddleware(TypedDict, total=False):
    """Retry middleware configuration."""
    max_attempts: int
    initial_interval_ms: int
    max_interval_ms: int
    multiplier: float


class Route(TypedDict, total=False):
    """Defines a single message processing route from an input to an output."""
    input: Required[Endpoint]
    output: Endpoint
    description: str
    concurrency: int
    batch_size: int
    commit_concurrency_limit: int
    startup_timeout_ms: int
    reconnect_interval_ms: int
    empty_batch_delay_ms: int
    allow_fault_injection: bool


class SledConfig(TypedDict, total=False):
    """General Sled database configuration"""
    path: Required[str]
    tree: Optional[str]
    read_from_start: bool
    delete_after_read: bool


class SqlxConfig(TypedDict, total=False):
    """General SQLx connection configuration."""
    url: Required[str]
    username: Optional[str]
    password: Optional[str]
    table: Required[str]
    insert_query: Optional[str]
    select_query: Optional[str]
    delete_after_read: bool
    auto_create_table: bool
    polling_interval_ms: Optional[int]
    tls: TlsConfig
    max_connections: Optional[int]
    min_connections: Optional[int]
    acquire_timeout_ms: Optional[int]
    idle_timeout_ms: Optional[int]
    max_lifetime_ms: Optional[int]


class StreamBufferConfig(TypedDict, total=False):
    """Configuration for the correlated in-process stream response buffer."""
    topic: Required[str]
    correlation_id: Optional[str]
    capacity: Optional[int]


class SwitchConfig(TypedDict, total=False):
    metadata_key: Required[str]
    cases: Required[Dict[str, Endpoint]]
    default: Optional[Endpoint]


class TlsConfig(TypedDict, total=False):
    """TLS configuration for secure connections."""
    required: bool
    ca_file: Optional[str]
    cert_file: Optional[str]
    key_file: Optional[str]
    cert_password: Optional[str]
    accept_invalid_certs: bool


class WeakJoinMiddleware(TypedDict, total=False):
    """Weak Join middleware configuration."""
    group_by: Required[str]
    expected_count: Required[int]
    timeout_ms: Required[int]


class WebSocketConfig(TypedDict, total=False):
    """WebSocket connection configuration."""
    url: Required[str]
    path: Optional[str]
    message_id_header: Optional[str]
    routed_queue_capacity: Optional[int]
    backlog: Optional[int]
    execution_mode: WebSocketExecutionMode


class ZeroMqConfig(TypedDict, total=False):
    url: Required[str]
    socket_type: Optional[ZeroMqSocketType]
    topic: Optional[str]
    bind: bool
    internal_buffer_size: Optional[int]


FaultMode = Literal["panic", "disconnect", "timeout", "json_format_error", "nack"]
FileFormat = Literal["normal", "json", "text", "raw"]
HttpServerProtocol = Literal["auto", "http1_only", "http2_only"]
MongoDbFormat = Literal["normal", "json", "text", "raw"]
MqttProtocol = Literal["v5", "v3"]
NatsDeliverPolicy = Literal["all", "last", "new", "last_per_subject"]
StaticConfig = Union[str, Dict[str, Any]]
WebSocketExecutionMode = Literal["auto", "direct_only", "routed"]
ZeroMqSocketType = Literal["push", "pull", "pub", "sub", "req", "rep"]


RouteConfig = Route
EndpointConfig = Endpoint
RoutesConfig = Dict[str, Route]

class ConfigDocument(TypedDict, total=False):
    """Top-level config accepted by from_config / from_yaml_str."""
    routes: Dict[str, Route]
    publishers: Dict[str, Endpoint]
